import 'package:flutter_app/ui/animal_cache_localized_names_asian.dart';

const Map<String, Map<String, List<String>>> animalCacheLocalizedDisplayNames =
    <String, Map<String, List<String>>>{
      ...animalCacheLocalizedDisplayNamesAsian,
      'de': <String, List<String>>{
        'animals': <String>[
          'Affe',
          'Büffel',
          'Gepard',
          'Delfin',
          'Elefant',
          'Frosch',
          'Giraffe',
          'Nilpferd',
          'Leguan',
        ],
        'instruments': <String>[
          'Klavier',
          'Banjo',
          'Violine',
          'Trompete',
          'Horn',
          'Schlagzeug',
          'Saxofon',
          'Tamburin',
          'Ukulele',
        ],
        'old_opera': <String>[
          'Bass',
          'Bariton',
          'Tenor',
          'Mezzosopran',
          'Sopran',
          'Hofsänger',
          'Moderne Opernfigur',
          'Maskierter Phantom-Stil',
          'Opern-Diva Comic',
        ],
        'butterflies': <String>[
          'Monarch',
          'Schwalbenschwanz',
          'Blauer Morpho',
          'Glasflügler',
          'Pfauenauge',
          'Zebra-Longwing',
          'Gelbling',
          'Blattfalter',
          'Metallfalter',
        ],
        'shells': <String>[
          'Kauri',
          'Jakobsmuschel',
          'Murex',
          'Nautilus',
          'Kegelschnecke',
          'Abalone',
          'Turbanschnecke',
          'Mondschnecke',
          'Herzmuschel',
        ],
      },
      'fr': <String, List<String>>{
        'animals': <String>[
          'Singe',
          'Buffle',
          'Guépard',
          'Dauphin',
          'Éléphant',
          'Grenouille',
          'Girafe',
          'Hippopotame',
          'Iguane',
        ],
        'instruments': <String>[
          'Piano',
          'Banjo',
          'Violon',
          'Trompette',
          'Cor',
          'Batterie',
          'Saxophone',
          'Tambourin',
          'Ukulélé',
        ],
        'old_opera': <String>[
          'Basse',
          'Baryton',
          'Ténor',
          'Mezzo-soprano',
          'Soprano',
          'Chanteur de cour',
          'Interprète d’opéra moderne',
          'Style fantôme masqué',
          'Diva d’opéra (comic)',
        ],
        'butterflies': <String>[
          'Monarque',
          'Machaon',
          'Morpho bleu',
          'Ailes de verre',
          'Paon-du-jour',
          'Zèbre longwing',
          'Soufré',
          'Papillon-feuille',
          'Métallique',
        ],
        'shells': <String>[
          'Porcelaine',
          'Coquille Saint-Jacques',
          'Murex',
          'Nautile',
          'Cône',
          'Ormeau',
          'Turbo',
          'Natice',
          'Coque',
        ],
      },
      'es': <String, List<String>>{
        'animals': <String>[
          'Mono',
          'Búfalo',
          'Guepardo',
          'Delfín',
          'Elefante',
          'Rana',
          'Jirafa',
          'Hipopótamo',
          'Iguana',
        ],
        'instruments': <String>[
          'Piano',
          'Banjo',
          'Violín',
          'Trompeta',
          'Trompa',
          'Batería',
          'Saxofón',
          'Pandereta',
          'Ukelele',
        ],
        'old_opera': <String>[
          'Bajo',
          'Barítono',
          'Tenor',
          'Mezzosoprano',
          'Soprano',
          'Cantante de corte',
          'Intérprete de ópera moderna',
          'Estilo fantasma enmascarado',
          'Diva de ópera (cómic)',
        ],
        'butterflies': <String>[
          'Monarca',
          'Cola de golondrina',
          'Morpho azul',
          'Alas de cristal',
          'Mariposa pavo real',
          'Zebra longwing',
          'Azufrada',
          'Mariposa hoja',
          'Metalmark',
        ],
        'shells': <String>[
          'Cauri',
          'Vieira',
          'Múrex',
          'Nautilo',
          'Cono',
          'Abulón',
          'Caracol turbante',
          'Caracol luna',
          'Berberecho',
        ],
      },
      'pt': <String, List<String>>{
        'animals': <String>[
          'Macaco',
          'Búfalo',
          'Guepardo',
          'Golfinho',
          'Elefante',
          'Sapo',
          'Girafa',
          'Hipopótamo',
          'Iguana',
        ],
        'instruments': <String>[
          'Piano',
          'Banjo',
          'Violino',
          'Trompete',
          'Trompa',
          'Bateria',
          'Saxofone',
          'Pandeireta',
          'Ukulele',
        ],
        'old_opera': <String>[
          'Baixo',
          'Barítono',
          'Tenor',
          'Mezzo-soprano',
          'Soprano',
          'Cantor da corte',
          'Intérprete de ópera moderna',
          'Estilo fantasma mascarado',
          'Diva de ópera (quadrinhos)',
        ],
        'butterflies': <String>[
          'Monarca',
          'Cauda-de-andorinha',
          'Morpho azul',
          'Asa de vidro',
          'Borboleta-pavão',
          'Zebra longwing',
          'Sulfúrea',
          'Borboleta-folha',
          'Metalmark',
        ],
        'shells': <String>[
          'Búzio',
          'Vieira',
          'Múrex',
          'Náutilo',
          'Concha-cone',
          'Abalone',
          'Concha-turbante',
          'Caracol-da-lua',
          'Berbigão',
        ],
      },
      'it': <String, List<String>>{
        'animals': <String>[
          'Scimmia',
          'Bufalo',
          'Ghepardo',
          'Delfino',
          'Elefante',
          'Rana',
          'Giraffa',
          'Ippopotamo',
          'Iguana',
        ],
        'instruments': <String>[
          'Pianoforte',
          'Banjo',
          'Violino',
          'Tromba',
          'Corno',
          'Batteria',
          'Sassofono',
          'Tamburello',
          'Ukulele',
        ],
        'old_opera': <String>[
          'Basso',
          'Baritono',
          'Tenore',
          'Mezzosoprano',
          'Soprano',
          'Cantante di corte',
          'Interprete d’opera moderna',
          'Stile fantasma mascherato',
          'Diva d’opera (fumetto)',
        ],
        'butterflies': <String>[
          'Monarca',
          'Macaone',
          'Morpho blu',
          'Ali di vetro',
          'Vanessa io',
          'Zebra longwing',
          'Solfurea',
          'Farfalla foglia',
          'Metalmark',
        ],
        'shells': <String>[
          'Ciprea',
          'Cappasanta',
          'Murice',
          'Nautilo',
          'Cono',
          'Abalone',
          'Turbo',
          'Natica',
          'Cuore di mare',
        ],
      },
    };
