const Map<String, Map<String, List<String>>> animalCacheLocalizedDisplayNames =
    <String, Map<String, List<String>>>{
      'ja': <String, List<String>>{
        'animals': <String>[
          'エイプ',
          'バッファロー',
          'チーター',
          'イルカ',
          'ゾウ',
          'カエル',
          'キリン',
          'カバ',
          'イグアナ',
        ],
        'instruments': <String>[
          'ピアノ',
          'バンジョー',
          'バイオリン',
          'トランペット',
          'ホルン',
          'ドラム',
          'サックス',
          'タンバリン',
          'ウクレレ',
        ],
        'old_opera': <String>[
          'バス',
          'バリトン',
          'テノール',
          'メゾソプラノ',
          'ソプラノ',
          '宮廷歌手',
          'モダンオペラ歌手',
          '仮面のファントム風',
          'オペラディーヴァ（コミック）',
        ],
        'butterflies': <String>[
          'モナーク',
          'アゲハ',
          'ブルーモルフォ',
          'グラスウィング',
          'クジャクチョウ',
          'シマアゲハ',
          'キチョウ',
          'コノハチョウ',
          'メタルマーク',
        ],
        'shells': <String>[
          'タカラガイ',
          'ホタテガイ',
          'ムレックス',
          'オウムガイ',
          'イモガイ',
          'アワビ',
          'サザエ',
          'ツメタガイ',
          'ザルガイ',
        ],
      },
      'de': <String, List<String>>{
        'animals': <String>[
          'Affe',
          'Büffel',
          'Gepard',
          'Delfin',
          'Elefant',
          'Frosch',
          'Giraffe',
          'Nilpferd',
          'Leguan',
        ],
        'instruments': <String>[
          'Klavier',
          'Banjo',
          'Violine',
          'Trompete',
          'Horn',
          'Schlagzeug',
          'Saxofon',
          'Tamburin',
          'Ukulele',
        ],
        'old_opera': <String>[
          'Bass',
          'Bariton',
          'Tenor',
          'Mezzosopran',
          'Sopran',
          'Hofsänger',
          'Moderne Opernfigur',
          'Maskierter Phantom-Stil',
          'Opern-Diva Comic',
        ],
        'butterflies': <String>[
          'Monarch',
          'Schwalbenschwanz',
          'Blauer Morpho',
          'Glasflügler',
          'Pfauenauge',
          'Zebra-Longwing',
          'Gelbling',
          'Blattfalter',
          'Metallfalter',
        ],
        'shells': <String>[
          'Kauri',
          'Jakobsmuschel',
          'Murex',
          'Nautilus',
          'Kegelschnecke',
          'Abalone',
          'Turbanschnecke',
          'Mondschnecke',
          'Herzmuschel',
        ],
      },
      'fr': <String, List<String>>{
        'animals': <String>[
          'Singe',
          'Buffle',
          'Guépard',
          'Dauphin',
          'Éléphant',
          'Grenouille',
          'Girafe',
          'Hippopotame',
          'Iguane',
        ],
        'instruments': <String>[
          'Piano',
          'Banjo',
          'Violon',
          'Trompette',
          'Cor',
          'Batterie',
          'Saxophone',
          'Tambourin',
          'Ukulélé',
        ],
        'old_opera': <String>[
          'Basse',
          'Baryton',
          'Ténor',
          'Mezzo-soprano',
          'Soprano',
          'Chanteur de cour',
          'Interprète d’opéra moderne',
          'Style fantôme masqué',
          'Diva d’opéra (comic)',
        ],
        'butterflies': <String>[
          'Monarque',
          'Machaon',
          'Morpho bleu',
          'Ailes de verre',
          'Paon-du-jour',
          'Zèbre longwing',
          'Soufré',
          'Papillon-feuille',
          'Métallique',
        ],
        'shells': <String>[
          'Porcelaine',
          'Coquille Saint-Jacques',
          'Murex',
          'Nautile',
          'Cône',
          'Ormeau',
          'Turbo',
          'Natice',
          'Coque',
        ],
      },
      'es': <String, List<String>>{
        'animals': <String>[
          'Mono',
          'Búfalo',
          'Guepardo',
          'Delfín',
          'Elefante',
          'Rana',
          'Jirafa',
          'Hipopótamo',
          'Iguana',
        ],
        'instruments': <String>[
          'Piano',
          'Banjo',
          'Violín',
          'Trompeta',
          'Trompa',
          'Batería',
          'Saxofón',
          'Pandereta',
          'Ukelele',
        ],
        'old_opera': <String>[
          'Bajo',
          'Barítono',
          'Tenor',
          'Mezzosoprano',
          'Soprano',
          'Cantante de corte',
          'Intérprete de ópera moderna',
          'Estilo fantasma enmascarado',
          'Diva de ópera (cómic)',
        ],
        'butterflies': <String>[
          'Monarca',
          'Cola de golondrina',
          'Morpho azul',
          'Alas de cristal',
          'Mariposa pavo real',
          'Zebra longwing',
          'Azufrada',
          'Mariposa hoja',
          'Metalmark',
        ],
        'shells': <String>[
          'Cauri',
          'Vieira',
          'Múrex',
          'Nautilo',
          'Cono',
          'Abulón',
          'Caracol turbante',
          'Caracol luna',
          'Berberecho',
        ],
      },
      'pt': <String, List<String>>{
        'animals': <String>[
          'Macaco',
          'Búfalo',
          'Guepardo',
          'Golfinho',
          'Elefante',
          'Sapo',
          'Girafa',
          'Hipopótamo',
          'Iguana',
        ],
        'instruments': <String>[
          'Piano',
          'Banjo',
          'Violino',
          'Trompete',
          'Trompa',
          'Bateria',
          'Saxofone',
          'Pandeireta',
          'Ukulele',
        ],
        'old_opera': <String>[
          'Baixo',
          'Barítono',
          'Tenor',
          'Mezzo-soprano',
          'Soprano',
          'Cantor da corte',
          'Intérprete de ópera moderna',
          'Estilo fantasma mascarado',
          'Diva de ópera (quadrinhos)',
        ],
        'butterflies': <String>[
          'Monarca',
          'Cauda-de-andorinha',
          'Morpho azul',
          'Asa de vidro',
          'Borboleta-pavão',
          'Zebra longwing',
          'Sulfúrea',
          'Borboleta-folha',
          'Metalmark',
        ],
        'shells': <String>[
          'Búzio',
          'Vieira',
          'Múrex',
          'Náutilo',
          'Concha-cone',
          'Abalone',
          'Concha-turbante',
          'Caracol-da-lua',
          'Berbigão',
        ],
      },
      'it': <String, List<String>>{
        'animals': <String>[
          'Scimmia',
          'Bufalo',
          'Ghepardo',
          'Delfino',
          'Elefante',
          'Rana',
          'Giraffa',
          'Ippopotamo',
          'Iguana',
        ],
        'instruments': <String>[
          'Pianoforte',
          'Banjo',
          'Violino',
          'Tromba',
          'Corno',
          'Batteria',
          'Sassofono',
          'Tamburello',
          'Ukulele',
        ],
        'old_opera': <String>[
          'Basso',
          'Baritono',
          'Tenore',
          'Mezzosoprano',
          'Soprano',
          'Cantante di corte',
          'Interprete d’opera moderna',
          'Stile fantasma mascherato',
          'Diva d’opera (fumetto)',
        ],
        'butterflies': <String>[
          'Monarca',
          'Macaone',
          'Morpho blu',
          'Ali di vetro',
          'Vanessa io',
          'Zebra longwing',
          'Solfurea',
          'Farfalla foglia',
          'Metalmark',
        ],
        'shells': <String>[
          'Ciprea',
          'Cappasanta',
          'Murice',
          'Nautilo',
          'Cono',
          'Abalone',
          'Turbo',
          'Natica',
          'Cuore di mare',
        ],
      },
      'hi': <String, List<String>>{
        'animals': <String>[
          'एप',
          'भैंसा',
          'चीता',
          'डॉल्फ़िन',
          'हाथी',
          'मेंढक',
          'जिराफ़',
          'दरियाई घोड़ा',
          'इगुआना',
        ],
        'instruments': <String>[
          'पियानो',
          'बैंजो',
          'वायलिन',
          'ट्रम्पेट',
          'हॉर्न',
          'ड्रम',
          'सैक्सोफोन',
          'टैम्बरीन',
          'यूकुलेले',
        ],
        'old_opera': <String>[
          'बास',
          'बैरिटोन',
          'टेनर',
          'मेज़ो-सोप्रानो',
          'सोप्रानो',
          'दरबारी गायक',
          'आधुनिक ओपेरा कलाकार',
          'मुखौटा फैंटम शैली',
          'ओपेरा दीवा कॉमिक',
        ],
        'butterflies': <String>[
          'मोनार्क',
          'स्वैलोटेल',
          'ब्लू मोर्फो',
          'ग्लासविंग',
          'पीकॉक तितली',
          'ज़ेब्रा लॉन्गविंग',
          'सल्फर तितली',
          'लीफ तितली',
          'मेटलमार्क तितली',
        ],
        'shells': <String>[
          'कौड़ी',
          'स्कैलप',
          'म्यूरेक्स',
          'नॉटिलस',
          'कोन शेल',
          'एबालोन',
          'टर्बन शेल',
          'मून स्नेल शेल',
          'कॉकल शेल',
        ],
      },
    };
