import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_app/ui/services/sudoku_victory_audio_service.dart';

void main() {
  test('maps victory mascot assets to expected audio clips', () {
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/1_cartoon_ape.png',
      ),
      'audio/animals/apes.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/2_cartoon_buffalo.png',
      ),
      'audio/animals/buffalo.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/3_cartoon_camel.png',
      ),
      'audio/animals/camel.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/4_cartoon_dolphin.png',
      ),
      'audio/animals/dolphin.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/5_cartoon_elephant.png',
      ),
      'audio/animals/elephant.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/6_cartoon_frog.png',
      ),
      'audio/animals/frog.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/7_cartoon_giraffe.png',
      ),
      'audio/animals/giraffe.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/8_cartoon_hippo.png',
      ),
      'audio/animals/hippos.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/9_cartoon_iguana.png',
      ),
      'audio/animals/iguana.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/music/piano.png',
      ),
      'audio/music/piano.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/music/saxaphone.png',
      ),
      'audio/music/saxophone.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/music/ukelele.png',
      ),
      'audio/music/ukulele.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/bass.png',
      ),
      'audio/opera/bass.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/baritone.png',
      ),
      'audio/opera/baritone.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/tenor.png',
      ),
      'audio/opera/tenor.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/mezzo_soprano.png',
      ),
      'audio/opera/mezzo_soprano.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/soprano.png',
      ),
      'audio/opera/soprano.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/royal_court_singer.png',
      ),
      'audio/opera/royal_court_singer.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/modern_opera.png',
      ),
      'audio/opera/modern_opera.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/masked_phantom_style.png',
      ),
      'audio/opera/masked_phantom_style.mp3',
    );
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/opera/opera_diva_comic.png',
      ),
      'audio/opera/opera_diva_comic.mp3',
    );
  });

  test('returns null for unknown mascot asset path', () {
    expect(SudokuVictoryAudioService.audioAssetForVictoryMascot(null), isNull);
    expect(
      SudokuVictoryAudioService.audioAssetForVictoryMascot(
        'assets/images/animals_chatGpT/unknown.png',
      ),
      isNull,
    );
  });
}
