// GENERATED CODE - DO NOT MODIFY BY HAND.
// Run: dart run tool/generate_background_music_tracks.dart

const Map<String, List<String>> kBackgroundTracksByFolder = {
  "butterflies": <String>[
    "audio/background/butterflies/blue_morpho_lullaby.mp3",
    "audio/background/butterflies/blue_morpho_lullaby_2.mp3",
    "audio/background/butterflies/drifting_leaf_waltz.mp3",
    "audio/background/butterflies/drifting_leaf_waltz_2.mp3",
    "audio/background/butterflies/flamboyant_glide.mp3",
    "audio/background/butterflies/flamboyant_glide_2.mp3",
    "audio/background/butterflies/glasswing_glide.mp3",
    "audio/background/butterflies/glasswing_glide_2.mp3",
    "audio/background/butterflies/monarchs_march.mp3",
    "audio/background/butterflies/monarchs_march_2.mp3",
    "audio/background/butterflies/savannah_flutter.mp3",
    "audio/background/butterflies/savannah_flutter_2.mp3",
    "audio/background/butterflies/sulphur_shuffle.mp3",
    "audio/background/butterflies/sulphur_shuffle_2.mp3",
    "audio/background/butterflies/swallowtail_swoop.mp3",
    "audio/background/butterflies/swallowtail_swoop_2.mp3",
  ],
  "opera": <String>[
    "audio/background/opera/Durch die Flut-2.mp3",
    "audio/background/opera/Durch die Flut.mp3",
    "audio/background/opera/Echo in the Dark-2.mp3",
    "audio/background/opera/Echo in the Dark.mp3",
    "audio/background/opera/Ha! Ha! Ha!-2.mp3",
    "audio/background/opera/Ha! Ha! Ha!.mp3",
    "audio/background/opera/L'Amour Rebelle-2.mp3",
    "audio/background/opera/L'Amour Rebelle.mp3",
    "audio/background/opera/Largo al Barbiere-2.mp3",
    "audio/background/opera/Largo al Barbiere.mp3",
    "audio/background/opera/O Patria Mia-2.mp3",
    "audio/background/opera/O Patria Mia.mp3",
    "audio/background/opera/The Blinding Flash-2.mp3",
    "audio/background/opera/The Blinding Flash.mp3",
    "audio/background/opera/il_mio_segreto.mp3",
    "audio/background/opera/il_mio_segreto_2.mp3",
    "audio/background/opera/o_mio_amore.mp3",
    "audio/background/opera/o_mio_amore_2.mp3",
  ],
  "shells": <String>[
    "audio/background/shells/Gentle Da Dum-2.mp3",
    "audio/background/shells/Gentle Da Dum.mp3",
    "audio/background/shells/Gentle Fins-2.mp3",
    "audio/background/shells/Gentle Fins.mp3",
    "audio/background/shells/Seashell Swish-5.mp3",
    "audio/background/shells/Seashell Swish-6.mp3",
    "audio/background/shells/Seashell Swish.mp3",
  ],
};
